# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

before_install:
- apt-get install libzmq3-dev

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
  on_success: change
  on_failure: change
